# -*- coding: utf-8 -*-
"""salesinsight

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkocayhBPg4CwVwkyJicwjp6eTIFaI65
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

def gerar_dataset_vendas(n_registros=200, seed=42):
    """Gera um dataset sintetico de vendas com dados sujos."""
    random.seed(seed)
    np.random.seed(seed)

    produtos = ["Notebook", "Smartphone", "Tablet", "Monitor",
                "Teclado", "Mouse", "Headset"]
    categorias = {"Notebook": "Computadores", "Smartphone": "Celulares",
                  "Tablet": "Celulares", "Monitor": "Computadores",
                  "Teclado": "Perifericos", "Mouse": "Perifericos",
                  "Headset": "Perifericos"}
    precos = {"Notebook": 3500, "Smartphone": 2200, "Tablet": 1800,
              "Monitor": 1200, "Teclado": 250, "Mouse": 120,
              "Headset": 350}
    regioes = ["Sudeste", "Sul", "Nordeste", "Centro-Oeste", "Norte"]

    data_inicio = datetime(2025, 1, 1)
    dados = []

    for i in range(n_registros):
        produto = random.choice(produtos)
        categoria = categorias[produto]
        quantidade = random.randint(1, 10)
        preco = round(precos[produto] * random.uniform(0.85, 1.15), 2)
        data = data_inicio + timedelta(days=random.randint(0, 364))
        data_txt = data.strftime("%Y-%m-%d")
        cliente = f"Cliente_{random.randint(1, 50):03d}"

        # --- sujeira proposital para a etapa de limpeza ---
        if random.random() < 0.05:
            quantidade = None                    # valor nulo
        if random.random() < 0.04:
            preco = None                         # valor nulo
        if random.random() < 0.06:
            produto = "  " + produto + " "       # espacos extras
        if random.random() < 0.03:
            data_txt = "DATA INVALIDA"           # data invalida
        if random.random() < 0.10:
            cliente = random.choice([            # ruido no nome
                cliente.upper().replace("_", "-"),
                cliente + "!!",
                "  " + cliente,
                cliente.replace("Cliente_", "cliente#"),
            ])

        dados.append({
            "id_venda": i + 1,
            "data_venda": data_txt,
            "cliente": cliente,
            "produto": produto,
            "categoria": categoria,
            "regiao": random.choice(regioes),
            "quantidade": quantidade,
            "preco_unitario": preco,
        })

    return pd.DataFrame(dados)


# Gerar e salvar o CSV bruto
df_bruto = gerar_dataset_vendas()
df_bruto.to_csv("vendas.csv", index=False)
print(f"Dataset gerado com {len(df_bruto)} registros.")
print(df_bruto.head())
df_limpo, relatorio_limpeza = limpar_dados(df_bruto)
df_limpo = criar_colunas_derivadas(df_limpo)

def inspecionar_dados(df):
    """Exibe as informacoes estruturais do DataFrame."""
    print("\n=== INSPECAO INICIAL DO DATASET ===")
    print(f"Shape: {df.shape}")
    print(f"\nColunas: {list(df.columns)}")
    print(f"\nTipos de dados:\n{df.dtypes}")
    print(f"\nValores nulos por coluna:\n{df.isnull().sum()}")
    print(f"\nPrimeiros registros:\n{df.head()}")
    return df

inspecionar_dados(df_bruto)

import re

def limpar_dados(df):
    """
    Limpa e trata o DataFrame de vendas.
    Retorna: (df_limpo, relatorio), onde relatorio e um dicionario
    com as contagens de registros iniciais, removidos e finais.
    """
    df_limpo = df.copy()
    # 1. remover espacos extras nas colunas de texto
    df_limpo["produto"] = df_limpo["produto"].str.strip()
    df_limpo["categoria"] = df_limpo["categoria"].str.strip()
    df_limpo["regiao"] = df_limpo["regiao"].str.strip()
    df_limpo["cliente"] = df_limpo["cliente"].str.strip()
    # 2. converter data_venda e descartar datas invalidas
    df_limpo["data_venda"] = pd.to_datetime(df_limpo["data_venda"], errors="coerce")
    df_limpo = df_limpo.dropna(subset=["data_venda"])
    # 3. descartar nulos em quantidade e preco_unitario
    df_limpo = df_limpo.dropna(subset=["quantidade", "preco_unitario"])
    # 4. ajustar os tipos numericos
    df_limpo["quantidade"] = df_limpo["quantidade"].astype(int)
    df_limpo["preco_unitario"] = df_limpo["preco_unitario"].astype(float)
    # 5. padronizar o nome do cliente com re.sub() e re.compile()
    df_limpo["cliente"] = df_limpo["cliente"].apply( lambda x: re.sub(r'[^a-zA-Z0-9_]', '', str(x).strip()))
    df_limpo["cliente"] = df_limpo["cliente"].apply( lambda x: re.sub(r'(?i)cliente_?', 'Cliente_', x))
    # 6. montar e imprimir o relatorio de limpeza
    linhas_iniciais = len(df)
    linhas_finais = len(df_limpo)
    linhas_removidas = linhas_iniciais - linhas_finais

    relatorio = {
        "registros_iniciais": linhas_iniciais,
        "registros_removidos": linhas_removidas,
        "registros_finais": linhas_finais
        }
    return df_limpo, relatorio

import numpy as np

def criar_colunas_derivadas(df) :
    """
    Cria novas colunas na planinlha para ajudar nas análises de venda.
    Recebe: df_limpo
    Retorna: df_derivado (DataFrame com as novas colunas)
    """
    df_derivado = df.copy()

    # 1 Calcular receita total de cada linha
    df_derivado["receita_total"] = df_derivado["quantidade"] * df_derivado["preco_unitario"]

    # 2 Extrair o ano e o número do mês da coluna de data
    df_derivado["ano"] = df_derivado["data_venda"].dt.year
    df_derivado["mes"] = df_derivado["data_venda"].dt.month

    # 3 Traduzir o número do mes para o nome em portugues
    dicionario_meses = { 1: "Janeiro", 2: "Fevereiro", 3: "Março", 4: "Abril", 5: "Maio", 6: "Junho",
    7: "Julho", 8: "Agosto", 9: "Setembro", 10: "Outubro", 11: "Novembro", 12: "Dezembro"}

    df_derivado["mes"] = df_derivado["mes"].map(dicionario_meses)

    # 4 Criar o trimestre mo formato q1-q4 (usando .dt.quarter e dicionário)
    df_derivado["trimestre"] = df_derivado["data_venda"].dt.quarter.map({1: "q1", 2: "q2", 3:"q3", 4: "q4"})

    #5 Classificação condicional da receita da linha com np.select
    condicoes = [
            df_derivado["receita_total"] < 500,
            (df_derivado["receita_total"] >= 500) & (df_derivado["receita_total"] < 5000),
            df_derivado["receita_total"] >= 5000,]
    faixas = ["Baixo Valor", "Medio Valor", "Alto Valor"]
    df_derivado["faixa_receita_item"] = np.select(condicoes, faixas, default="Nao Classificado")

    return df_derivado

def calcular_metricas(df) :
  """
  Calcula as métricas de vendas agrupadas por mês, produto, categoria e região.
  Retorna um dicionário contendo os DataFrames de cada análise.
  """
  # Criamos um dicionário vazio para guardar nossos resultados
  metricas = {}

  # 1. Métricas por Mês (Receita total, quantidade vendida e número de vendas)
  metricas["por_mes"] = df.groupby("mes").agg(
          receita_total=("receita_total", "sum"),
          quantidade_vendida=("quantidade", "sum"),
          n_vendas=("id_venda", "count")
      ).reset_index()

  # 2. Top 5 Produtos por Receita (em ordem decrescente)
  metricas["top_produtos"] = df.groupby("produto").agg(
          receita_total=("receita_total", "sum")
      ).sort_values(by="receita_total", ascending=False).head(5).reset_index()

  # 3. Receita Total por Categoria
  metricas["por_categoria"] = df.groupby("categoria").agg(
          receita_total=("receita_total", "sum")
      ).reset_index()

  # 4. Receita Total e Ticket Médio (média de gasto por venda) por Região
  metricas["por_regiao"] = df.groupby("regiao").agg(
          receita_total=("receita_total", "sum"),
          ticket_medio=("receita_total", "mean")
      ).reset_index()

  # Devolvemos os resultados prontos
  return metricas

def segmentar_clientes(df):
    """
    Agrupa os dados por cliente, soma o faturamento total de cada um
    e os classifica em Bronze, Prata ou Ouro usando lambda.
    Retorna um DataFrame com cliente, total_gasto e segmento.
    """
    # 1. Agrupar por cliente e somar o faturamento total acumulado
    clientes_df = df.groupby("cliente")["receita_total"].sum().reset_index()

    # 2. Renomear a coluna para 'total_gasto' (exatamente como o professor pede)
    clientes_df = clientes_df.rename(columns={"receita_total": "total_gasto"})

    # 3. Classificar usando .apply() com a função lambda
    clientes_df["segmento"] = clientes_df["total_gasto"].apply(
        lambda valor: "Bronze" if valor < 5000
        else ("Prata" if valor <= 15000 else "Ouro")
    )

    clientes_df = clientes_df.sort_values("total_gasto", ascending=False)
    return clientes_df

def segmentar_clientes_fix(df):
    """
    Agrupa os dados por cliente, soma o faturamento total de cada um
    e os classifica em Bronze, Prata ou Ouro usando lambda.
    Retorna um DataFrame com cliente, total_gasto e segmento.
    """
    # 1. Agrupar por cliente e somar faturamento acumulado [4]
    clientes_df = df.groupby("cliente")["receita_total"].sum().reset_index()

    # 2. Renomear para o nome exato exigido [3]
    clientes_df = clientes_df.rename(columns={"receita_total": "total_gasto"})

    # 3. Classificar usando a função lambda [4]
    clientes_df["segmento"] = clientes_df["total_gasto"].apply(
        lambda valor: "Bronze" if valor < 5000
        else ("Prata" if valor <= 15000 else "Ouro")
    )

    return clientes_df

def calcular_estatisticas_numpy(df):
    """Aplica operacoes NumPy sobre a coluna receita_total."""

    # 1. transformar a coluna em array NumPy
    receitas = df["receita_total"].to_numpy()

    # 2. funcoes de agregacao do NumPy (pelo menos 3 - aqui temos 6)
    media = np.mean(receitas)
    mediana = np.median(receitas)
    desvio_padrao = np.std(receitas)
    total = np.sum(receitas)
    minimo = np.min(receitas)
    maximo = np.max(receitas)

    # 3. broadcasting: mesma conta aplicada em todos os valores de uma vez
    receitas_normalizadas = (receitas - minimo) / (maximo - minimo)

    # 4. filtragem booleana: so as vendas acima da media
    acima_da_media = receitas[receitas > media]

    # 5. mostrar os resultados
    print("Média:", media)
    print("Mediana:", mediana)
    print("Desvio padrão:", desvio_padrao)
    print("Total:", total)
    print("Mínimo:", minimo)
    print("Máximo:", maximo)
    print("Quantidade de vendas acima da média:", len(acima_da_media))

    # 6. devolver tudo organizado num dicionario, pra usar depois
    return {
        "media": media,
        "mediana": mediana,
        "desvio_padrao": desvio_padrao,
        "total": total,
        "minimo": minimo,
        "maximo": maximo,
        "qtd_acima_da_media": len(acima_da_media),
    }

estatisticas = calcular_estatisticas_numpy(df_limpo)
# 2. Segmentação de Clientes (Bronze, Prata, Ouro)
df_clientes = segmentar_clientes(df_limpo)

# 3. Mostrar os 10 maiores clientes (RF06)
print("\n--- TOP 10 MAIORES CLIENTES ---")
print(df_clientes.head(10))

# 4. Mostrar contagem por segmento
print("\n--- DISTRIBUIÇÃO POR SEGMENTO ---")
print(df_clientes["segmento"].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

def criar_visualizacoes(df):
    """Gera e salva as visualizacoes obrigatorias do projeto (RF08)."""
    sns.set_theme(style="whitegrid")

    # 1. ORDENAR OS MESES CRONOLOGICAMENTE
    ordem_meses = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
                   'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']

    df_mes = df.groupby("mes")["receita_total"].sum().reset_index()
    df_mes['mes'] = pd.Categorical(df_mes['mes'], categories=ordem_meses, ordered=True)
    df_mes = df_mes.sort_values('mes')

    # --- FIGURA 1: receita_por_mes.png ---
    plt.figure(figsize=(10, 5))
    sns.lineplot(data=df_mes, x="mes", y="receita_total", marker="o", color="navy")
    plt.title("Receita Total por Mês")
    plt.xlabel("Mês")
    plt.ylabel("Receita (R$)")
    plt.xticks(rotation=45)
    sns.despine() # Remove bordas superior e direita (Requisito de boas praticas)
    plt.tight_layout()
    plt.savefig("receita_por_mes.png", dpi=150, bbox_inches="tight")
    plt.show()

    # --- FIGURA 2: top_produtos.png ---
    plt.figure(figsize=(10, 5))
    df_prod = df.groupby("produto")["receita_total"].sum().reset_index().sort_values("receita_total", ascending=False).head(5)
    sns.barplot(data=df_prod, x="produto", y="receita_total", hue="produto", legend=False, palette="viridis")
    plt.title("Top 5 Produtos por Receita")
    plt.xlabel("Produto")
    plt.ylabel("Receita Total (R$)")
    sns.despine()
    plt.tight_layout()
    plt.savefig("top_produtos.png", dpi=150, bbox_inches="tight")
    plt.show()

    # --- FIGURA 3: quantidade_vs_receita.png ---
    plt.figure(figsize=(10, 5))
    sns.scatterplot(data=df, x="quantidade", y="receita_total", hue="categoria", s=100)
    plt.title("Quantidade vs. Receita Total por Categoria")
    plt.xlabel("Quantidade")
    plt.ylabel("Receita (R$)")
    sns.despine()
    plt.tight_layout()
    plt.savefig("quantidade_vs_receita.png", dpi=150, bbox_inches="tight")
    plt.show()

    # --- FIGURA 4: painel_resumo.png (Subplots 2x2) ---
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle("SalesInsight PY - Painel Resumo", fontsize=16)

    # Subplot 1: Linha
    sns.lineplot(data=df_mes, x="mes", y="receita_total", ax=axes[0, 0], marker="o")
    axes[0, 0].set_title("Receita por Mês")
    axes[0, 0].tick_params(axis='x', rotation=45)

    # Subplot 2: Barras
    sns.barplot(data=df_prod, x="produto", y="receita_total", ax=axes[0, 1], hue="produto", legend=False)
    axes[0, 1].set_title("Top 5 Produtos")

    # Subplot 3: Dispersão
    sns.scatterplot(data=df, x="quantidade", y="receita_total", hue="categoria", ax=axes[1, 0])
    axes[1, 0].set_title("Quantidade vs Receita")

    # Subplot 4: Região
    df_reg = df.groupby("regiao")["receita_total"].sum().reset_index()
    sns.barplot(data=df_reg, x="regiao", y="receita_total", ax=axes[1, 1], hue="regiao", legend=False)
    axes[1, 1].set_title("Receita por Região")

    # Remover bordas de todos os subplots
    for ax in axes.flat:
        sns.despine(ax=ax)

    plt.tight_layout()
    plt.savefig("painel_resumo.png", dpi=150, bbox_inches="tight")
    plt.show()

# Executar a geração das imagens
criar_visualizacoes(df_limpo)

import pandas as pd
import numpy as np

# PARTE A: FUNÇÃO DE ORDEM SUPERIOR (RF09)


def aplicar_transformacao_coluna(df, nome_coluna, funcao_transformacao):
    """
    Funcao de Ordem Superior: Recebe outra funcao como argumento
    e a aplica em uma coluna do DataFrame usando .apply().
    """
    df_copia = df.copy()
    df_copia[nome_coluna] = df_copia[nome_coluna].apply(funcao_transformacao)
    return df_copia



# PARTE B: CLASSE ANALISADOR DE VENDAS (RF09)


class AnalisadorDeVendas:
    def __init__(self, caminho_arquivo):
        self.caminho_arquivo = caminho_arquivo
        self.df_bruto = None
        self.df_limpo = None
        self.clientes = None
        self.metricas = {}

    def carregar(self):
        """Carrega o dataset inicial."""
        self.df_bruto = pd.read_csv(self.caminho_arquivo)
        print(f"[Analisador] {len(self.df_bruto)} registros lidos com sucesso.")

    def limpar(self):
        """Aplica limpeza e tratamento nos dados."""
        resultado = limpar_dados(self.df_bruto)

        # Se retornar uma tupla, pega apenas o primeiro elemento (DataFrame)
        if isinstance(resultado, tuple):
            self.df_limpo = resultado[0]
        else:
            self.df_limpo = resultado

        print("[Analisador] Limpeza de dados realizada.")

    def transformar(self):
        """Cria colunas derivadas."""
        # Coloque aqui a sua função de transformação/colunas derivadas
        if 'criar_colunas_derivadas' in globals():
            self.df_limpo = criar_colunas_derivadas(self.df_limpo)
        print("[Analisador] Colunas derivadas criadas.")

    def analisar(self):
        """Calcula metricas agregadas, estatisticas e segmentacao."""
        self.metricas['estatisticas'] = calcular_estatisticas_numpy(self.df_limpo)
        self.clientes = segmentar_clientes(self.df_limpo)
        print("[Analisador] Análise estatística e segmentação concluídas.")

    def visualizar(self):
        """Gera e exporta os 4 graficos (RF08)."""
        criar_visualizacoes(self.df_limpo)
        print("[Analisador] Visualizações geradas.")

    def resumo(self):
        """Imprime um resumo executivo do que foi processado (RF09)."""
        receita = 0.0
        if 'estatisticas' in self.metricas and 'total' in self.metricas['estatisticas']:
            receita = self.metricas['estatisticas']['total']

        print("\n" + "=" * 55)
        print("          RESUMO EXECUTIVO DO ANALISADOR")
        print("=" * 55)
        print(f"Total de Registros Brutos: {len(self.df_bruto) if self.df_bruto is not None else 0}")
        print(f"Total de Registros Limpos: {len(self.df_limpo) if self.df_limpo is not None else 0}")
        print(f"Clientes Segmentados:     {len(self.clientes) if self.clientes is not None else 0}")
        print(f"Receita Total:            R$ {receita:,.2f}")
        print("=" * 55)

# Instanciando e rodando a classe
analisador = AnalisadorDeVendas("vendas.csv")
analisador.carregar()
analisador.limpar()
analisador.transformar()
analisador.analisar()
analisador.resumo()

import os
import json

# ==============================================================================
# RF10 – Exportar Resultados em CSV e JSON
# ==============================================================================
def exportar_resultados(metricas, clientes, estatisticas):
    """Exporta os resultados processados para a pasta outputs (RF10)."""
    os.makedirs("outputs", exist_ok=True)

    # Exporta DataFrames para CSV
    if isinstance(metricas, pd.DataFrame):
        metricas.to_csv("outputs/metricas_por_mes.csv", index=False, encoding="utf-8-sig")
    if isinstance(clientes, pd.DataFrame):
        clientes.to_csv("outputs/segmentacao_clientes.csv", index=False, encoding="utf-8-sig")

    # Exporta estatísticas numéricas para JSON
    serializavel = {k: round(float(v), 2) for k, v in estatisticas.items()}
    caminho_json = "outputs/estatisticas_gerais.json"

    with open(caminho_json, "w", encoding="utf-8") as f:
        json.dump(serializavel, f, indent=4, ensure_ascii=False)

    # Leitura de confirmação
    with open(caminho_json, "r", encoding="utf-8") as f:
        conferencia = json.load(f)
        print(f"\n[OK] Arquivo JSON exportado e verificado: {conferencia}")

# ==============================================================================
# RF11 – Executar o Fluxo Completo (Ponto de Entrada)
# ==============================================================================
def main():
    """Executa o pipeline completo do SalesInsight PY (RF11)."""
    print("=" * 60)
    print("   SALESINSIGHT PY - Análise de Dados de Vendas")
    print("=" * 60)

    # Instanciando e executando a classe
    analisador = AnalisadorDeVendas("vendas.csv")
    analisador.carregar()
    analisador.limpar()
    analisador.transformar()
    analisador.analisar()
    analisador.resumo()

    # Gerando os arquivos de saída
    df_mes = analisador.df_limpo.groupby("mes")["receita_total"].sum().reset_index()
    exportar_resultados(df_mes, analisador.clientes, analisador.metricas['estatisticas'])

    print("\n[CONCLUÍDO] Projeto executado com sucesso!")

if __name__ == "__main__":
    main()

def main():
    """Executa o fluxo completo do SalesInsight PY (RF11)."""
    print("=" * 60)
    print("   SALESINSIGHT PY - Análise de Dados de Vendas")
    print("=" * 60)

    # 1. Instanciando e executando o pipeline da classe
    analisador = AnalisadorDeVendas("vendas.csv")
    analisador.carregar()
    analisador.limpar()
    analisador.transformar()
    analisador.analisar()
    analisador.resumo()

    # 2. Agrupamento para métricas por mês
    if 'mes' in analisador.df_limpo.columns and 'receita_total' in analisador.df_limpo.columns:
        df_mes = analisador.df_limpo.groupby("mes")["receita_total"].sum().reset_index()
    else:
        df_mes = analisador.df_limpo

    # 3. Exportação final dos arquivos (RF10)
    exportar_resultados(df_mes, analisador.clientes, analisador.metricas.get('estatisticas', {}))

    print("\n[CONCLUÍDO] Fluxo do RF11 executado com sucesso!")

# Ponto de entrada
if __name__ == "__main__":
    main()